defaults:
  - defaults 
  - _self_ 

name: "unfrozen_l2_pretrain"
student: true
load_classifier_checkpoint_path: "wandb_logs/Connectivity_Distillation_Distillation_Exp/73wg850x/checkpoints/last.ckpt"
freeze_classifier_backbone: false
project_name: "Connectivity_Distillation_Distillation_Exp"