defaults:
  - defaults 

name: "train_classifier_dino_prop"
student: true
distillation_loss_name: 'prop_topo'
distance_fn_name: 'euclidean'
distillation_loss_config: {scale_matching_method: "distribution", importance_calculation_strat: "component_size",match_scale_in_space: 2}
distillation_loss_weight: 1
teacher_model_type: "dinobloom"
kill_classification_loss: false