defaults:
  - defaults 
  - _self_ 
  
name: "train_classifier_dino_mds"
student: true
distillation_loss_name: 'mds'
distance_fn_name: 'euclidean'
teacher_model_type: "dinobloom"
distillation_loss_weight: "uncert_based"
