defaults:
  - defaults 

name: "train_classifier_dino_prop"
student: true
distillation_loss_name: 'prop_topo'
distance_fn_name: 'cosine'
distillation_loss_weight: "uncert_based"
teacher_model_type: "dinobloom"
kill_classification_loss: false