defaults:
  - defaults 
  - _self_ 
  
name: "distill_dino_resnet18"
student: true
distillation_loss_name: 'prop_topo'
distillation_loss_config: {scale_matching_method: "order", importance_calculation_strat: "multiplication",match_scale_in_space: 1}
distance_fn_name: 'euclidean'
distillation_loss_weight: 1
teacher_model_type: "dino-S"
classifier_max_epoch: 200
kill_classification_loss: true
take_last_checkpoint: false