defaults:
  - defaults
  - _self_ 

name: "vanilla"
student: true
image_encoder_name: "ResNet18" #"ShuffleNetV2_x1.5"
dataset_name: "Acevedo" 
k_fold: 5
classifier_max_epoch: 250
classifier_lr: 0.00001