method: bayes  # or grid/random
project: new_param_sweep
program: sweep_injection.py
metric:
  name: test_loss
  goal: minimize
parameters:
  config_path:
    values: ["configs/hydra"]
  config_name:
    values: ["ae"]
  ae_latent_dim:
    values: [16, 32, 64, 128]
  ae_lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.001
  ae_weight_decay:
    distribution: log_uniform_values
    min: 1e-7
    max: 1e-4