method: bayes  # or grid/random/bayes
project: opt_best_dist_loss
program: sweep_injection.py
metric:
  name: dm_metrics_loocv_knn_acc
  goal: maximize
parameters:
  config_path:
    values: ["configs/hydra"]
  config_name:
    values: ["distill_dino_to_res18_euc"]
  classifier_max_epoch:
    values: [400]
  take_last_checkpoint:
    values: [true]
  kill_classification_loss:
    values: [true]
  classifier_lr:
    values: [0.0001,0.00001,0.000001]
  classifier_weight_decay:
    values: [0.0001,0.00001,0.000001,0.0]
  classifier_batch_size:
    values: [16,32,64,96]
  distillation_loss_config.augmentation_factor:
    values: [0.05,0.005,0.0005,0.0]

  