method: bayes  # or grid/random
project: optimize_dinobackbone_sweep
program: sweep_injection.py
metric:
  name: test_accuracy
  goal: maximize
parameters:
  config_path:
    values: ["configs/hydra"]
  config_name:
    values: ["dinobloom_backbone"]
  classifier_max_epoch:
    values: [500]
  classifier_lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.001
  classifier_weight_decay:
    distribution: log_uniform_values
    min: 1e-7
    max: 1e-3
