method: bayes  # or grid/random
project: optimize_dist_sweep
program: sweep_injection.py
metric:
  name: train_distillation_loss
  goal: minimize
parameters:
  config_path:
    values: ["configs/hydra"]
  config_name:
    values: ["dino_prop_topo"]
  classifier_max_epoch:
    values: [200]
  take_last_checkpoint:
    values: [true]
  kill_classification_loss:
    values: [true]
  classifier_lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.001
  classifier_weight_decay:
    distribution: log_uniform_values
    min: 1e-7
    max: 1e-3
