defaults:
  - defaults 
  - _self_ 

name: "dist_dino2res_moor"
student: true
project_name: "Connectivity_Distillation_Distillation_Exp"
distillation_loss_name: 'moor_topo'
distance_fn_name: 'euclidean'
distillation_loss_weight: 1
teacher_model_type: "dinobloom"
classifier_max_epoch: 800
kill_classification_loss: true
take_last_checkpoint: true